version: "3"

services:
  nginx:
    image: "nginx"
    container_name: nginx
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      # - "443:443" # Public HTTPS Port
    volumes:
      - ./data:/data

  database:
    # image: mysql:5.7
    image: mariadb
    container_name: db
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root

  wordpress:
    image: wordpress:latest
    container_name: wp
    depends_on:
      - database
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_db
      WORDPRESS_DB_PASSWORD: wp_db

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "9005:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 300M

volumes:
  dbdata:
