version: "3"

services:
  nginx:
    image: "nginx"
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./wordpress:/var/www/html
    networks:
      - wp_net

  database:
    image: mariadb
    container_name: db
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wp_net

  wordpress:
    image: wordpress:latest
    container_name: wp
    depends_on:
      - database
    volumes:
      - ./wordpress:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_db
      WORDPRESS_DB_PASSWORD: wp_db
    networks:
      - wp_net

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "9005:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 300M
    networks:
      - wp_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - wp_net

volumes:
  dbdata:

networks:
  wp_net:
    driver: bridge
